version: 0.2

phases:
  install: 
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - cat package.json
      - npm install
      - ls
      - echo "We would use 'npm test' here to run our tests (if we had any)"
  build: 
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync ./build s3://thistempbucket


