version: 0.2

phases:
  install: 
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - npm install
      - echo "We would use 'npm test' here to run our tests (if we had any)"
  build: 
    commands:
      - npm run build

artifacts:
  base-directory: build
  files:
    - '**/*'
